### ISSUE TITLE
Drupal 8.4x breaking css for anonymous 

### ISSUE THREAD

**Issue by mdyoung3** [asu-ke-web-services/asu_brand#2]
Steps to reproduce:

1. Enable module
2. Set block
3. Log out and view page as anonymous user

If you go into inspect on Chrome, you see the following error: "Failed to load resource: the server responded with a status of 403 (Forbidden)"

**Comment by mdyoung3** [comment]
Adding the footer block does not affect the front-end.

I am checking to see if it is a caching issue by turning off caching.

**Comment by mdyoung3** [comment]
Disabling caching didn't have any affect.

**Comment by mmenavas** [comment]
It looks like the issue occurs when using the Bootstrap theme version 8.x-3.6.

**Comment by mdyoung3** [comment]
When you remove the css for I.E. 9, styles will load correctly. Drupal 8.4 no longer supports I.E. 9.
